---

- name: Run Pre-Change Analysis
  hosts: ndi
  gather_facts: false
  vars:
    insights_fabric_group: ACI-Fabrics
    prechange_file: "/var/lib/awx/output/{{ change_name }}.json"

  tasks:
    - name: Create a new Pre-Change Analysis from file
      cisco.nd.nd_pcv:
        ig_name: "{{ insights_fabric_group }}"
        site_name: "{{ site }}"
        name: "{{ change_name }}"
        file: "{{ prechange_file }}"
        state: present
    
    - name: Show the pre-change file data.
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', prechange_file) }}"
      
    - name: Delete the pre-change file.
      ansible.builtin.file:
        path: "{{ prechange_file }}"
        state: absent

    - name: Validate a Pre-Change Analysis
      cisco.nd.nd_pcv_delta_analysis:
        insights_group: "{{ insights_fabric_group }}"
        site_name: "{{ site }}"
        name: "{{ change_name }}"
        state: validate
        exclude_ack_anomalies: True
        epoch_choice: epoch2
      register: pcv_result
