---
# ACI Tenant playbook
- name: Create ansible tenant and its dependencies
  hosts: Bloomington
  connection: local

  tasks:
    - name: Create Tenant and its dependencies
      ansible.builtin.import_tasks: tasks/tenant.yaml
      vars:
        tenant: "{{ tenant }}"
        tenant_alias: "{{ tenant_alias }}"
        tenant_description: "{{ tenant_description }}"
        vrf: "{{ vrf }}"
        vrf_description: "{{ vrf_description }}"
        prechange_file: "/var/lib/awx/output/{{ change_name }}.json"
