---
# tasks file for External EPG

- name: Setup Connection to APIC
  ansible.builtin.set_fact:
    auth: &auth
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      private_key: "{{ aci_private_key }}"
      validate_certs: "{{ aci_validate_certs }}"
      output_path: "{{ prechange_file if ansible_check_mode else change_file }}"

- name: "{{ 'Create External EPG for ' + l3out }}"
  cisco.aci.aci_l3out_extepg:
    <<: *auth
    tenant: "{{ tenant }}"
    l3out: "{{ l3out }}"
    name: "{{ extepg }}"

- name: "{{ 'Add subnet to External EPG for ' + l3out }}"
  cisco.aci.aci_l3out_extsubnet:
    <<: *auth
    tenant: "{{ tenant }}"
    l3out: "{{ l3out }}"
    extepg: "{{ extepg }}"
    network: "{{ item.subnet }}"
  loop: "{{ networks }}"

- name: "{{ 'Associate contracts to External EPG for ' + l3out }}"
  cisco.aci.aci_l3out_extepg_to_contract:
    <<: *auth
    tenant: "{{ tenant }}"
    l3out: "{{ l3out }}"
    extepg: "{{ extepg }}"
    contract: "{{ item.contract }}"
    contract_type: "{{ item.direction }}"
  loop: "{{ contracts }}"
